version: "3.9"

services:

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - conf/env/.dev-env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis
    ports:
      - 6379:6379

  rabbit:
        hostname: rabbit
        image: rabbitmq:management
        env_file:
          - conf/env/.dev-env
        ports:
            - 15672:15672
            - 5672:5672
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure


volumes:
  postgres_data:
